In [1]:
import numpy as np

In [2]:
a = np.random.randn(3, 2)
b = np.random.randn(2, 3)
print(a)
print(b)

[[-1.55560716 -0.95836863]
 [ 2.03049792 -0.67215443]
 [-0.01296576 -0.05850642]]
[[-0.09126923  0.30468877  1.51862107]
 [-0.99354028 -0.88345486 -1.67947965]]


In [3]:
c = np.dot(a, b)
print(c)

[[ 1.09415691  0.37269939 -0.75281718]
 [ 0.48249053  1.21248801  4.21242661]
 [ 0.05931186  0.04773726  0.07857027]]


In [4]:
s = np.sum(c, axis=0, keepdims=True)
print(s)

[[1.63595929 1.63292466 3.5381797 ]]


In [5]:
r = np.repeat(s, 3, axis=0)
print(r)

[[1.63595929 1.63292466 3.5381797 ]
 [1.63595929 1.63292466 3.5381797 ]
 [1.63595929 1.63292466 3.5381797 ]]


In [6]:
x = np.array([1, 3])
y = np.array([3, 5])
y[...] = x
print(y)

[1 3]


In [7]:
d = np.random.permutation(10).astype(np.float32)
print(d)
print(d.dtype)

[6. 1. 9. 3. 2. 8. 5. 4. 7. 0.]
float32


# クラメールの公式というやつ

In [8]:
params = np.array([[1, 2, 1], [1, 1, 0], [1,1,1]])
print(params)

[[1 2 1]
 [1 1 0]
 [1 1 1]]


In [9]:
ans = [270, 150, 220]
print(ans)

[270, 150, 220]


In [10]:
d0 = np.copy(params)
d1 = np.copy(params)
d2 = np.copy(params)
d0[:,0] = ans
d1[:,1] = ans
d2[:,2] = ans
print(d0,d1,d2)

[[270   2   1]
 [150   1   0]
 [220   1   1]] [[  1 270   1]
 [  1 150   0]
 [  1 220   1]] [[  1   2 270]
 [  1   1 150]
 [  1   1 220]]


In [11]:
x0, x1, x2 = np.round(np.linalg.det(d0) / np.linalg.det(params)), np.round(np.linalg.det(d1) / np.linalg.det(params)), np.round(np.linalg.det(d2) / np.linalg.det(params))
print(x0, x1, x2)

100.0 50.0 70.0
