In [3]:
from __future__ import print_function
import torch

In [58]:
x = torch.rand(5, 3)
x

tensor([[0.7588, 0.7715, 0.1480],
        [0.8237, 0.6177, 0.4599],
        [0.6373, 0.8375, 0.4644],
        [0.4324, 0.6670, 0.0386],
        [0.9907, 0.3339, 0.5353]])

In [28]:
zeros = torch.zeros(100, 200, dtype=torch.long)
zeros

tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]])

In [33]:
t = torch.tensor([5.2, 10])
t

tensor([ 5.2000, 10.0000])

In [50]:
ones = t.new_ones(3, 4, dtype=torch.double)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [51]:
torch.randn_like(ones)

tensor([[-0.1213, -1.0637, -0.4180,  0.4100],
        [ 0.8920, -0.5890,  0.1344, -0.4195],
        [ 1.5739,  0.7122, -0.8681,  0.1724]], dtype=torch.float64)

In [57]:
x.size()

torch.Size([5, 3])

In [59]:
x.add_(10)

tensor([[10.7588, 10.7715, 10.1480],
        [10.8237, 10.6177, 10.4599],
        [10.6373, 10.8375, 10.4644],
        [10.4324, 10.6670, 10.0386],
        [10.9907, 10.3339, 10.5353]])

In [65]:
r = torch.randn(4, 4)
s = r.view(16)
t = s.view(-1, 8)
print(r.size(), s.size(), t.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [72]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.4192])
-0.41920310258865356


In [74]:
x.numpy()
print(x.numpy(), x)

[-0.4192031] tensor([-0.4192])


In [75]:
print(torch.from_numpy(r.numpy()))

tensor([[-1.5912, -0.5748, -0.4975, -0.9637],
        [ 1.5424,  0.0457,  3.4584,  1.1365],
        [ 0.7266,  0.2362, -1.0336, -1.1988],
        [-0.9084, -0.4111, -1.8862,  2.2009]])


In [76]:
torch.cuda.is_available()

False