In [1]:
import numpy as np

# 1-1

In [2]:
a = np.array([62, 85, 95, 60]).reshape(2, 2)
a

array([[62, 85],
       [95, 60]])

In [3]:
b = np.array([50, 80, 55, 20]).reshape(2, 2)
b

array([[50, 80],
       [55, 20]])

In [4]:
a + b

array([[112, 165],
       [150,  80]])

In [24]:
c = np.random.randint(0, 100, size=(3, 5))
c

array([[74, 23, 67, 21,  7],
       [64, 26, 72, 56, 31],
       [94, 66, 65,  7, 44]])

# 1-2（skip）

 # 1-3

In [6]:
np.array([[1, 2], [3, 4]]) + np.array([[0, 0], [0, 0]]) 

array([[1, 2],
       [3, 4]])

In [7]:
np.array([[0, 0], [0, 0]])  + np.array([[1, 2], [3, 4]]) 

array([[1, 2],
       [3, 4]])

In [8]:
 np.array([[1, 2], [3, 4]]) +  np.array([[1, 2], [3, 4]]) 

array([[2, 4],
       [6, 8]])

In [9]:
 np.array([1, 2, 3, 4]).reshape(2, 2) +  np.array([1, 2, 3, 4]).reshape(2, 2)

array([[2, 4],
       [6, 8]])

In [10]:
 np.array([[2, -7], [1, -8]]) +  np.array([[-2, 7], [-1, 8]]) 

array([[0, 0],
       [0, 0]])

In [11]:
 np.array([2, -7, 1, -8]).reshape(2, 2) +  np.array([-2, 7, -1, 8]).reshape(2, 2)

array([[0, 0],
       [0, 0]])

In [12]:
ans = np.array([1, 0, 0, 1]).reshape(2, 2) \
+ np.array([1, 0, 0, 1]).reshape(2, 2) \
+ np.array([1, 0, 0, 1]).reshape(2, 2) \
+ np.array([1, 0, 0, 1]).reshape(2, 2) \
+ np.array([1, 0, 0, 1]).reshape(2, 2)
ans

array([[5, 0],
       [0, 5]])

# 1-4

In [26]:
np.arange(1, 5).reshape(2, 2) + np.sort(np.arange(-4, 0))[::-1].reshape(2, 2)

array([[0, 0],
       [0, 0]])

# 2

In [28]:
np.dot(np.array([1,2,3,4]).reshape(2,2), np.array([1,4,0,5]).reshape(2,2))

array([[ 1, 14],
       [ 3, 32]])

In [36]:
x1 = np.random.randint(0, 100, size=(2, 100))
x2 = np.random.randint(0, 100, size=(100, 2))
x3 = np.random.randint(0, 100, size=(2, 3))
np.dot(np.dot(x1, x2), x3)

array([[35560865, 11858523, 29374368],
       [30768765, 10224423, 26357848]])

In [64]:
a, b, c, d = 0, -1, 1, 0

hoge = np.array([a, b, c, d]).reshape(2, 2)
hoge_inv = np.linalg.inv(hoge)

hoge_inv_calc = np.array([d, -b, -c, a]).reshape(2, 2) / ((a * d) - (b * c))

(hoge, hoge_inv, np.round(np.dot(hoge, hoge_inv)).astype("int"))

(array([[ 0, -1],
        [ 1,  0]]),
 array([[ 0.,  1.],
        [-1., -0.]]),
 array([[1, 0],
        [0, 1]]))

In [60]:
wallets = np.array([
    [1, 3, 5, 7, 9],
    [9, 7, 5, 3, 1],
    [1, 1, 1, 1, 1],
])
coins = np.array([
    [1, 5, 10, 50, 100],
    [2, 3, 5, 4, 5]
])

np.dot(wallets, coins.T)

array([[1316,  109],
       [ 344,   81],
       [ 166,   19]])