In [1]:
import numpy as np

# 1-1

In [2]:
a = np.array([62, 85, 95, 60]).reshape(2, 2)
a

array([[62, 85],
       [95, 60]])

In [3]:
b = np.array([50, 80, 55, 20]).reshape(2, 2)
b

array([[50, 80],
       [55, 20]])

In [4]:
a + b

array([[112, 165],
       [150,  80]])

In [24]:
c = np.random.randint(0, 100, size=(3, 5))
c

array([[74, 23, 67, 21,  7],
       [64, 26, 72, 56, 31],
       [94, 66, 65,  7, 44]])

# 1-2（skip）

 # 1-3

In [6]:
np.array([[1, 2], [3, 4]]) + np.array([[0, 0], [0, 0]]) 

array([[1, 2],
       [3, 4]])

In [7]:
np.array([[0, 0], [0, 0]])  + np.array([[1, 2], [3, 4]]) 

array([[1, 2],
       [3, 4]])

In [8]:
 np.array([[1, 2], [3, 4]]) +  np.array([[1, 2], [3, 4]]) 

array([[2, 4],
       [6, 8]])

In [9]:
 np.array([1, 2, 3, 4]).reshape(2, 2) +  np.array([1, 2, 3, 4]).reshape(2, 2)

array([[2, 4],
       [6, 8]])

In [10]:
 np.array([[2, -7], [1, -8]]) +  np.array([[-2, 7], [-1, 8]]) 

array([[0, 0],
       [0, 0]])

In [11]:
 np.array([2, -7, 1, -8]).reshape(2, 2) +  np.array([-2, 7, -1, 8]).reshape(2, 2)

array([[0, 0],
       [0, 0]])

In [12]:
ans = np.array([1, 0, 0, 1]).reshape(2, 2) \
+ np.array([1, 0, 0, 1]).reshape(2, 2) \
+ np.array([1, 0, 0, 1]).reshape(2, 2) \
+ np.array([1, 0, 0, 1]).reshape(2, 2) \
+ np.array([1, 0, 0, 1]).reshape(2, 2)
ans

array([[5, 0],
       [0, 5]])

# 1-4

In [26]:
np.arange(1, 5).reshape(2, 2) + np.sort(np.arange(-4, 0))[::-1].reshape(2, 2)

array([[0, 0],
       [0, 0]])