In [2]:
import torch
import torch.nn as nn

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("NYCTaxiFares.csv")

In [5]:
df.head()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
0  2010-04-19 08:17:56 UTC          6.5           0        -73.992365   
1  2010-04-17 15:43:53 UTC          6.9           0        -73.990078   
2  2010-04-17 11:23:26 UTC         10.1           1        -73.994149   
3  2010-04-11 21:25:03 UTC          8.9           0        -73.990485   
4  2010-04-17 02:19:01 UTC         19.7           1        -73.990976   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  
0        40.730521         -73.975499         40.744746                1  
1        40.740558         -73.974232         40.744114                1  
2        40.751118         -73.960064         40.766235                2  
3        40.756422         -73.971205         40.748192                1  
4        40.734202         -73.905956         40.743115                1

In [6]:
df["fare_amount"].describe()

count    120000.000000
mean         10.040326
std           7.500134
min           2.500000
25%           5.700000
50%           7.700000
75%          11.300000
max          49.900000
Name: fare_amount, dtype: float64

In [7]:
def haversine_distance(df, lat1, long1, lat2, long2):
    """
    Calculates the haversine distance between 2 sets of GPS coordinates in df
    """
    r = 6371  # average radius of Earth in kilometers
       
    phi1 = np.radians(df[lat1])
    phi2 = np.radians(df[lat2])
    
    delta_phi = np.radians(df[lat2]-df[lat1])
    delta_lambda = np.radians(df[long2]-df[long1])
     
    a = np.sin(delta_phi/2)**2 + np.cos(phi1) * np.cos(phi2) * np.sin(delta_lambda/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))
    d = (r * c) # in kilometers

    return d

In [8]:
df.columns

Index(['pickup_datetime', 'fare_amount', 'fare_class', 'pickup_longitude',
       'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude',
       'passenger_count'],
      dtype='object')

In [9]:
df["dist_km"] = haversine_distance(df, "pickup_latitude", "pickup_longitude", "dropoff_latitude", "dropoff_longitude")

In [11]:
df.head()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
0  2010-04-19 08:17:56 UTC          6.5           0        -73.992365   
1  2010-04-17 15:43:53 UTC          6.9           0        -73.990078   
2  2010-04-17 11:23:26 UTC         10.1           1        -73.994149   
3  2010-04-11 21:25:03 UTC          8.9           0        -73.990485   
4  2010-04-17 02:19:01 UTC         19.7           1        -73.990976   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  \
0        40.730521         -73.975499         40.744746                1   
1        40.740558         -73.974232         40.744114                1   
2        40.751118         -73.960064         40.766235                2   
3        40.756422         -73.971205         40.748192                1   
4        40.734202         -73.905956         40.743115                1   

    dist_km  
0  2.126312  
1  1.392307  
2  3.326763  
3  1.864129  
4  7.231321

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   pickup_datetime    120000 non-null  object 
 1   fare_amount        120000 non-null  float64
 2   fare_class         120000 non-null  int64  
 3   pickup_longitude   120000 non-null  float64
 4   pickup_latitude    120000 non-null  float64
 5   dropoff_longitude  120000 non-null  float64
 6   dropoff_latitude   120000 non-null  float64
 7   passenger_count    120000 non-null  int64  
 8   dist_km            120000 non-null  float64
dtypes: float64(6), int64(2), object(1)
memory usage: 8.2+ MB


In [14]:
df["pickup_datetime"] = pd.to_datetime(df["pickup_datetime"])

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype              
---  ------             --------------   -----              
 0   pickup_datetime    120000 non-null  datetime64[ns, UTC]
 1   fare_amount        120000 non-null  float64            
 2   fare_class         120000 non-null  int64              
 3   pickup_longitude   120000 non-null  float64            
 4   pickup_latitude    120000 non-null  float64            
 5   dropoff_longitude  120000 non-null  float64            
 6   dropoff_latitude   120000 non-null  float64            
 7   passenger_count    120000 non-null  int64              
 8   dist_km            120000 non-null  float64            
dtypes: datetime64[ns, UTC](1), float64(6), int64(2)
memory usage: 8.2 MB


In [16]:
df.head()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
0 2010-04-19 08:17:56+00:00          6.5           0        -73.992365   
1 2010-04-17 15:43:53+00:00          6.9           0        -73.990078   
2 2010-04-17 11:23:26+00:00         10.1           1        -73.994149   
3 2010-04-11 21:25:03+00:00          8.9           0        -73.990485   
4 2010-04-17 02:19:01+00:00         19.7           1        -73.990976   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  \
0        40.730521         -73.975499         40.744746                1   
1        40.740558         -73.974232         40.744114                1   
2        40.751118         -73.960064         40.766235                2   
3        40.756422         -73.971205         40.748192                1   
4        40.734202         -73.905956         40.743115                1   

    dist_km  
0  2.126312  
1  1.392307  
2  3.326763  
3  1.864129  
4  7.231321

In [18]:
mytime = df["pickup_datetime"][0]

In [20]:
df["EDTdate"] = df["pickup_datetime"] - pd.Timedelta(hours=4)

In [21]:
df.head()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
0 2010-04-19 08:17:56+00:00          6.5           0        -73.992365   
1 2010-04-17 15:43:53+00:00          6.9           0        -73.990078   
2 2010-04-17 11:23:26+00:00         10.1           1        -73.994149   
3 2010-04-11 21:25:03+00:00          8.9           0        -73.990485   
4 2010-04-17 02:19:01+00:00         19.7           1        -73.990976   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  \
0        40.730521         -73.975499         40.744746                1   
1        40.740558         -73.974232         40.744114                1   
2        40.751118         -73.960064         40.766235                2   
3        40.756422         -73.971205         40.748192                1   
4        40.734202         -73.905956         40.743115                1   

    dist_km                   EDTdate  
0  2.126312 2010-04-19 04:17:56+00:00  
1  1.392307 2010-04-17 11:43:53+00:00  
2  3.326763 2010-04-17 07:23:26+00:00  
3  1.864129 2010-04-11 17:25:03+00:00  
4  7.231321 2010-04-16 22:19:01+00:00

In [22]:
df["Hour"] = df["EDTdate"].dt.hour

In [24]:
df["AMorPM"] = np.where(df["Hour"] < 12, "AM", "PM")

In [25]:
df.head()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
0 2010-04-19 08:17:56+00:00          6.5           0        -73.992365   
1 2010-04-17 15:43:53+00:00          6.9           0        -73.990078   
2 2010-04-17 11:23:26+00:00         10.1           1        -73.994149   
3 2010-04-11 21:25:03+00:00          8.9           0        -73.990485   
4 2010-04-17 02:19:01+00:00         19.7           1        -73.990976   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  \
0        40.730521         -73.975499         40.744746                1   
1        40.740558         -73.974232         40.744114                1   
2        40.751118         -73.960064         40.766235                2   
3        40.756422         -73.971205         40.748192                1   
4        40.734202         -73.905956         40.743115                1   

    dist_km                   EDTdate  Hour AMorPM  
0  2.126312 2010-04-19 04:17:56+00:00     4     AM  
1  1.392307 2010-04-17 11:43:53+00:00    11     AM  
2  3.326763 2010-04-17 07:23:26+00:00     7     AM  
3  1.864129 2010-04-11 17:25:03+00:00    17     PM  
4  7.231321 2010-04-16 22:19:01+00:00    22     PM

In [27]:
df["Weekday"] = df["EDTdate"].dt.strftime("%a")

In [28]:
df.head()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
0 2010-04-19 08:17:56+00:00          6.5           0        -73.992365   
1 2010-04-17 15:43:53+00:00          6.9           0        -73.990078   
2 2010-04-17 11:23:26+00:00         10.1           1        -73.994149   
3 2010-04-11 21:25:03+00:00          8.9           0        -73.990485   
4 2010-04-17 02:19:01+00:00         19.7           1        -73.990976   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  \
0        40.730521         -73.975499         40.744746                1   
1        40.740558         -73.974232         40.744114                1   
2        40.751118         -73.960064         40.766235                2   
3        40.756422         -73.971205         40.748192                1   
4        40.734202         -73.905956         40.743115                1   

    dist_km                   EDTdate  Hour AMorPM Weekday  
0  2.126312 2010-04-19 04:17:56+00:00     4     AM     Mon  
1  1.392307 2010-04-17 11:43:53+00:00    11     AM     Sat  
2  3.326763 2010-04-17 07:23:26+00:00     7     AM     Sat  
3  1.864129 2010-04-11 17:25:03+00:00    17     PM     Sun  
4  7.231321 2010-04-16 22:19:01+00:00    22     PM     Fri

In [83]:
categorical_cols = ["Hour", "AMorPM", "Weekday"]
continuous_cols = ['pickup_latitude', 'pickup_longitude', 'dropoff_latitude', 'dropoff_longitude', 'passenger_count', 'dist_km']
y_col = ["fare_amount"]

In [84]:
for cat in categorical_cols:
    df[cat] = df[cat].astype("category")

In [85]:
df.head()

pickup_datetime  fare_amount  fare_class  pickup_longitude  \
0 2010-04-19 08:17:56+00:00          6.5           0        -73.992365   
1 2010-04-17 15:43:53+00:00          6.9           0        -73.990078   
2 2010-04-17 11:23:26+00:00         10.1           1        -73.994149   
3 2010-04-11 21:25:03+00:00          8.9           0        -73.990485   
4 2010-04-17 02:19:01+00:00         19.7           1        -73.990976   

   pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  \
0        40.730521         -73.975499         40.744746                1   
1        40.740558         -73.974232         40.744114                1   
2        40.751118         -73.960064         40.766235                2   
3        40.756422         -73.971205         40.748192                1   
4        40.734202         -73.905956         40.743115                1   

    dist_km                   EDTdate Hour AMorPM Weekday  
0  2.126312 2010-04-19 04:17:56+00:00    4     AM     Mon  
1  1.392307 2010-04-17 11:43:53+00:00   11     AM     Sat  
2  3.326763 2010-04-17 07:23:26+00:00    7     AM     Sat  
3  1.864129 2010-04-11 17:25:03+00:00   17     PM     Sun  
4  7.231321 2010-04-16 22:19:01+00:00   22     PM     Fri

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype              
---  ------             --------------   -----              
 0   pickup_datetime    120000 non-null  datetime64[ns, UTC]
 1   fare_amount        120000 non-null  float64            
 2   fare_class         120000 non-null  int64              
 3   pickup_longitude   120000 non-null  float64            
 4   pickup_latitude    120000 non-null  float64            
 5   dropoff_longitude  120000 non-null  float64            
 6   dropoff_latitude   120000 non-null  float64            
 7   passenger_count    120000 non-null  int64              
 8   dist_km            120000 non-null  float64            
 9   EDTdate            120000 non-null  datetime64[ns, UTC]
 10  Hour               120000 non-null  category           
 11  AMorPM             120000 non-null  category           
 12  Weekday            120000 non-

In [87]:
df["Weekday"].head()

0    Mon
1    Sat
2    Sat
3    Sun
4    Fri
Name: Weekday, dtype: category
Categories (7, object): ['Fri', 'Mon', 'Sat', 'Sun', 'Thu', 'Tue', 'Wed']

In [88]:
df["Weekday"].cat.codes

0         1
1         2
2         2
3         3
4         0
         ..
119995    3
119996    0
119997    3
119998    5
119999    2
Length: 120000, dtype: int8

In [89]:
hr = df["Hour"].cat.codes.values
ampm = df["AMorPM"].cat.codes.values
wkdy = df["Weekday"].cat.codes.values

In [90]:
categories = np.stack([hr,ampm, wkdy], axis=1)

In [91]:
categories

array([[ 4,  0,  1],
       [11,  0,  2],
       [ 7,  0,  2],
       ...,
       [14,  1,  3],
       [ 4,  0,  5],
       [12,  1,  2]], dtype=int8)

In [92]:
categories = torch.tensor(categories, dtype=torch.int64)

In [100]:
continuaces = np.stack([df[col].values for col in continuous_cols], axis=1)

In [101]:
continuaces = torch.tensor(continuaces, dtype=torch.float)

In [102]:
y = torch.tensor(df[y_col].values, dtype=torch.float)

In [103]:
y.size()

torch.Size([120000, 1])

In [104]:
category_sizes = [len(df[col].cat.categories) for col in categorical_cols]

In [105]:
category_sizes

[24, 2, 7]

In [106]:
embedding_size = [(size, min(50, size+1) // 2) for size in category_sizes]

In [107]:
embedding_size

[(24, 12), (2, 1), (7, 4)]

In [108]:
categoriesz = categories[:4]

In [109]:
categoriesz

tensor([[ 4,  0,  1],
        [11,  0,  2],
        [ 7,  0,  2],
        [17,  1,  3]])

In [110]:
continuaces[:5]

tensor([[ 40.7305, -73.9924,  40.7447, -73.9755,   1.0000,   2.1263],
        [ 40.7406, -73.9901,  40.7441, -73.9742,   1.0000,   1.3923],
        [ 40.7511, -73.9941,  40.7662, -73.9601,   2.0000,   3.3268],
        [ 40.7564, -73.9905,  40.7482, -73.9712,   1.0000,   1.8641],
        [ 40.7342, -73.9910,  40.7431, -73.9060,   1.0000,   7.2313]])

In [111]:
self_embeds = nn.ModuleList([nn.Embedding(ni, nf) for ni, nf in embedding_size])

In [112]:
embeddingz = []
for i, e in enumerate(self_embeds):
    print(e)
    em = e(categoriesz[:,i])
    print(em.size())
    embeddingz.append(em)

Embedding(24, 12)
torch.Size([4, 12])
Embedding(2, 1)
torch.Size([4, 1])
Embedding(7, 4)
torch.Size([4, 4])


In [113]:
embeddingz

[tensor([[ 0.2585, -1.9904, -0.1888, -0.1182,  1.3115,  1.7543,  0.3121,  0.5426,
           0.5642,  1.0028, -0.5899,  0.3113],
         [ 0.7007, -0.7002,  0.0755,  0.2502, -0.3133,  1.0430, -0.8291, -0.6206,
           1.8052, -1.3444, -1.7783, -1.5487],
         [-1.1681, -0.2103,  0.4585, -0.3132, -1.4211,  0.0249, -1.5468, -1.2943,
           1.3873,  0.4714, -2.8445, -0.4647],
         [ 1.0493, -0.9240,  0.0742, -0.0476, -1.1323, -0.7339, -1.2622,  1.4807,
          -0.8679,  0.1949, -0.9980, -0.6362]], grad_fn=<EmbeddingBackward>),
 tensor([[-0.2593],
         [-0.2593],
         [-0.2593],
         [ 0.8707]], grad_fn=<EmbeddingBackward>),
 tensor([[-0.0732,  0.8490,  1.0583,  0.8386],
         [-0.3626,  0.6264, -0.1084,  1.2463],
         [-0.3626,  0.6264, -0.1084,  1.2463],
         [ 0.1267, -1.2910,  0.1142, -0.5047]], grad_fn=<EmbeddingBackward>)]

In [114]:
z = torch.cat(embeddingz, 1)

In [115]:
z

tensor([[ 0.2585, -1.9904, -0.1888, -0.1182,  1.3115,  1.7543,  0.3121,  0.5426,
          0.5642,  1.0028, -0.5899,  0.3113, -0.2593, -0.0732,  0.8490,  1.0583,
          0.8386],
        [ 0.7007, -0.7002,  0.0755,  0.2502, -0.3133,  1.0430, -0.8291, -0.6206,
          1.8052, -1.3444, -1.7783, -1.5487, -0.2593, -0.3626,  0.6264, -0.1084,
          1.2463],
        [-1.1681, -0.2103,  0.4585, -0.3132, -1.4211,  0.0249, -1.5468, -1.2943,
          1.3873,  0.4714, -2.8445, -0.4647, -0.2593, -0.3626,  0.6264, -0.1084,
          1.2463],
        [ 1.0493, -0.9240,  0.0742, -0.0476, -1.1323, -0.7339, -1.2622,  1.4807,
         -0.8679,  0.1949, -0.9980, -0.6362,  0.8707,  0.1267, -1.2910,  0.1142,
         -0.5047]], grad_fn=<CatBackward>)